export const data = {
    title: "Nice Hair Salon",
    tagline: "Hair, considered.",
    shortDescription: "A Mississauga hair salon offering various hair services for men, women, and children.",
    description: "Nice Hair Salon is a Mississauga hair salon offering precision haircuts, colour, highlights, perms, straightening, bridal makeup and updos. Walk-ins welcome.",
    location: "3635 Cawthra Rd, Mississauga, ON L5A 2Y5",
    streetAddress: "3635 Cawthra Rd",
    city: "Mississauga",
    region: "ON",
    postalCode: "L5A 2Y5",
    country: "CA",
    phoneNumber: "(437) 241-5189",
    tel: "tel:+14372415189",
    facebook: "https://www.facebook.com/profile.php?id=61556935263279",
    instagram: "https://www.instagram.com/nicehairsalon.ca/",
    siteUrl: "https://nicehairsalon.ca",
    hours: "Mo-Su 09:00-20:00",
    hoursReadable: "Monday to Sunday, 9 a.m. to 8 p.m.",
};
